"""empty message

Revision ID: 04616c77529d
Revises: 725f6b94246a
Create Date: 2019-09-23 15:50:34.088435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04616c77529d'
down_revision = '725f6b94246a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
