"""empty message

Revision ID: 2c6e0ad6731b
Revises: 04616c77529d
Create Date: 2019-09-25 13:29:03.243144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6e0ad6731b'
down_revision = '04616c77529d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_category',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=20), nullable=False),
    sa.Column('cat_name', sa.String(length=20), nullable=False),
    sa.Column('keywords', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cat_sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('dir', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_category')
    # ### end Alembic commands ###
