"""empty message

Revision ID: 7940e6780dc7
Revises: 03e42705f2e9
Create Date: 2019-09-29 20:13:46.023092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7940e6780dc7'
down_revision = '03e42705f2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('vatar', sa.String(length=80), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=2), nullable=True),
    sa.Column('telephont', sa.String(length=11), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
