"""empty message

Revision ID: c3061ed48a29
Revises: cb27366d230b
Create Date: 2019-09-27 14:24:39.299004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3061ed48a29'
down_revision = 'cb27366d230b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_auth_add_time'), 'auth', ['add_time'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('auths', sa.String(length=600), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_add_time'), 'role', ['add_time'], unique=False)
    op.add_column('user', sa.Column('is_super', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('reg_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'reg_time')
    op.drop_column('user', 'is_super')
    op.drop_index(op.f('ix_role_add_time'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_auth_add_time'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
