"""empty message

Revision ID: f8fea6573dd4
Revises: 2c6e0ad6731b
Create Date: 2019-09-26 10:20:05.154708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8fea6573dd4'
down_revision = '2c6e0ad6731b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.SmallInteger(), nullable=True),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('article',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('shorttitle', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('keywords', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('allowcomments', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['cat_id'], ['article_category.cat_id'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('article_tag',
    sa.Column('article.aid', sa.Integer(), nullable=False),
    sa.Column('tag.tid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article.aid'], ['article.aid'], ),
    sa.ForeignKeyConstraint(['tag.tid'], ['tag.tid'], ),
    sa.PrimaryKeyConstraint('article.aid', 'tag.tid')
    )
    op.alter_column('article_category', 'cat_sort',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('article_category', 'cat_sort',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_table('article_tag')
    op.drop_table('article')
    op.drop_table('tag')
    # ### end Alembic commands ###
